### Import Libraries

In [1]:
import os
import re
import json
import time
import sys
import subprocess
import numpy as np
import pandas as pd

def ensure_pkg(import_name, pip_name=None):
    pip_name = pip_name or import_name
    try:
        __import__(import_name)
        return True
    except ModuleNotFoundError:
        print(f"Installing {pip_name} into the active notebook environment...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", pip_name, "-q"])
            __import__(import_name)
            return True
        except Exception as e:
            print(f"Could not install {pip_name}: {e}")
            return False

OPENAI_AVAILABLE = ensure_pkg("openai", "openai")
SKLEARN_AVAILABLE = ensure_pkg("sklearn", "scikit-learn")
SCIPY_AVAILABLE = ensure_pkg("scipy", "scipy")

from openai import OpenAI

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import ComplementNB
from sklearn.multioutput import ClassifierChain
from sklearn.metrics import (
    classification_report,
    precision_recall_fscore_support,
    accuracy_score,
    f1_score,
    hamming_loss,
    precision_score,
    recall_score,
    jaccard_score
)
from scipy.sparse import hstack

print(f"OPENAI_AVAILABLE={OPENAI_AVAILABLE} | SKLEARN_AVAILABLE={SKLEARN_AVAILABLE} | SCIPY_AVAILABLE={SCIPY_AVAILABLE}")

OPENAI_AVAILABLE=True | SKLEARN_AVAILABLE=True | SCIPY_AVAILABLE=True

### Quick run order
1. Set your API key in the environment: `OPENAI_API_KEY`
2. Run all cells from top to bottom
3. This notebook uses **curated few-shot only** (no RAG / retrieval)
4. It auto-saves outputs with a consistent prefix

### Section 1. Data Cleaning

In [2]:
# ==========================================
# LIGHT PREPROCESSING (preserve toxic signal)
# ==========================================

# Earlier aggressive cleaning can be harmful for toxicity detection because
# profanity, obfuscation, repeated characters, and punctuation often carry the signal.
# We therefore use lighter preprocessing and keep two views of the text:
# 1) LLM view   : minimal cleanup for prompting
# 2) Sparse view: light normalization for TF-IDF based baselines

def _strip_urls(text):
    return re.sub(r"http\S+|www\S+", " ", text)

def normalize_for_llm(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = _strip_urls(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def normalize_for_sparse(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = _strip_urls(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Backward-compatible alias used elsewhere in the notebook
def clean_text_fast(text):
    return normalize_for_sparse(text)

# Optional saved lightweight cleaned training file for reproducibility
try:
    _tmp_train = pd.read_csv("train.csv", engine="python", on_bad_lines="skip")
    _tmp_train["comment_text"] = _tmp_train["comment_text"].astype(str).apply(normalize_for_sparse)
    _tmp_train.to_csv("train_cleaned_light.csv", index=False)
    print("✅ Saved lightweight cleaned training file: train_cleaned_light.csv")
except Exception as e:
    print(f"Skipping optional train_cleaned_light.csv export: {e}")

✅ Saved lightweight cleaned training file: train_cleaned_light.csv

In [3]:
# ==========================================
# CONFIGURATION
# ==========================================

API_KEY = os.environ.get("OPENAI_API_KEY","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")
if not API_KEY:
    raise ValueError(
        "OPENAI_API_KEY is not set. In a notebook cell, run:\n"
        "import os\n"
        "os.environ['OPENAI_API_KEY'] = 'your_key_here'"
    )

MODEL = os.environ.get("OPENAI_MODEL", "gpt-4.1")

CATEGORIES = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

PRECISION_PRIORITY_LABELS = {"severe_toxic", "threat", "insult"}

MAX_CHARS = 1200
REQUEST_DELAY = 0.35
RETRIES = 3
SEED = 42

# Main evaluation size
EVAL_NATURAL_N = 2000

# Stress-test subset size
CHALLENGE_N_POS = 180
CHALLENGE_N_NEG = 250

# Checkpointing / progress
SAVE_EVERY = 50
PROGRESS_EVERY = 10
DEFAULT_PREFIX = f"eval2000_{MODEL.replace('.', '_')}_lightprep"
SAVE_PREFIX = os.environ.get("SAVE_PREFIX", DEFAULT_PREFIX)

# Few-shot controls
USE_JSON_MODE = os.environ.get("USE_JSON_MODE", "1").strip() == "1"
SEVERE_RECHECK = os.environ.get("SEVERE_RECHECK", "0").strip() == "1"
SEVERE_RECHECK_MODES = {"few-shot"}
FEWSHOT_VARIANT = os.environ.get("FEWSHOT_VARIANT", "precision_8")
FEWSHOT_STRATEGY = FEWSHOT_VARIANT  # backward-compatible alias

# Pilot / run controls
RUN_VALIDATION_PILOT = os.environ.get("RUN_VALIDATION_PILOT", "0").strip() == "1"
RUN_CHALLENGE_EVAL = os.environ.get("RUN_CHALLENGE_EVAL", "0").strip() == "1"
RESUME_RUN = os.environ.get("RESUME_RUN", "0").strip() == "1"
FORCE_FRESH_RUN = os.environ.get("FORCE_FRESH_RUN", "1").strip() == "1"

try:
    client = OpenAI(api_key=API_KEY)
except Exception as e:
    raise RuntimeError(f"Could not initialize OpenAI client: {e}")

LLM_TEXT_COL = "comment_text"
SPARSE_TEXT_COL = "comment_text_sparse"

print(f"MODEL={MODEL} | FEWSHOT_VARIANT={FEWSHOT_VARIANT}")
print(f"SAVE_PREFIX={SAVE_PREFIX} | RESUME_RUN={RESUME_RUN} | FORCE_FRESH_RUN={FORCE_FRESH_RUN}")
print(f"EVAL_NATURAL_N={EVAL_NATURAL_N} | SAVE_EVERY={SAVE_EVERY} | PROGRESS_EVERY={PROGRESS_EVERY}")
print(f"USE_JSON_MODE={USE_JSON_MODE} | SEVERE_RECHECK={SEVERE_RECHECK} | RECHECK_MODES={sorted(SEVERE_RECHECK_MODES)}")
print(f"LLM_TEXT_COL={LLM_TEXT_COL} | SPARSE_TEXT_COL={SPARSE_TEXT_COL}")

MODEL=gpt-4.1 | FEWSHOT_VARIANT=precision_8
SAVE_PREFIX=eval2000_gpt-4_1_lightprep | RESUME_RUN=False | FORCE_FRESH_RUN=True
EVAL_NATURAL_N=2000 | SAVE_EVERY=50 | PROGRESS_EVERY=10
USE_JSON_MODE=True | SEVERE_RECHECK=False | RECHECK_MODES=['few-shot']
LLM_TEXT_COL=comment_text | SPARSE_TEXT_COL=comment_text_sparse

In [4]:
# ==========================================
# RUN FILE MANAGEMENT
# ==========================================

def cleanup_run_files(prefix):
    patterns = [
        f"{prefix}_zero-shot_preds.csv", f"{prefix}_zero-shot_raw.csv", f"{prefix}_zero-shot_errors.csv",
        f"{prefix}_few-shot_preds.csv", f"{prefix}_few-shot_raw.csv", f"{prefix}_few-shot_errors.csv",
        f"{prefix}_valpilot_zero-shot_preds.csv", f"{prefix}_valpilot_zero-shot_raw.csv", f"{prefix}_valpilot_zero-shot_errors.csv",
        f"{prefix}_valpilot_few-shot_preds.csv", f"{prefix}_valpilot_few-shot_raw.csv", f"{prefix}_valpilot_few-shot_errors.csv",
        f"{prefix}_zero_shot_predictions.csv", f"{prefix}_few_shot_predictions.csv", f"{prefix}_tfidf_logreg_predictions.csv",
        f"{prefix}_evaluation_subset.csv", f"{prefix}_challenge_subset.csv", f"{prefix}_validation_pilot_subset.csv",
        f"{prefix}_zero_per_class_metrics.csv", f"{prefix}_few_per_class_metrics.csv", f"{prefix}_lr_per_class_metrics.csv",
        f"{prefix}_results_summary.csv", f"{prefix}_lr_thresholds.csv", f"{prefix}_fewshot_bank.csv",
        f"{prefix}_fewshot_tidy.csv", f"{prefix}_fewshot_tidy.xlsx",
        f"{prefix}_zeroshot_tidy.csv", f"{prefix}_zeroshot_tidy.xlsx",
        f"{prefix}_tfidf_logreg_tidy.csv", f"{prefix}_tfidf_logreg_tidy.xlsx",
        f"{prefix}_zero_error_analysis_detailed.csv", f"{prefix}_zero_error_summary_stats.csv",
        f"{prefix}_few_error_analysis_detailed.csv", f"{prefix}_few_error_summary_stats.csv",
        f"{prefix}_lr_error_analysis_detailed.csv", f"{prefix}_lr_error_summary_stats.csv",
    ]
    removed = []
    for p in patterns:
        if os.path.exists(p):
            os.remove(p)
            removed.append(p)
    return removed

if FORCE_FRESH_RUN and not RESUME_RUN:
    removed = cleanup_run_files(SAVE_PREFIX)
    if removed:
        print(f"Removed {len(removed)} old files for a fresh run with prefix '{SAVE_PREFIX}'.")
    else:
        print(f"No existing files found for prefix '{SAVE_PREFIX}'. Fresh run will start from scratch.")
elif RESUME_RUN:
    print(f"Resume mode is ON for prefix '{SAVE_PREFIX}'. Existing prediction files will be reused if present.")
else:
    print(f"Fresh run mode selected for prefix '{SAVE_PREFIX}'.")

No existing files found for prefix 'eval2000_gpt-4_1_lightprep'. Fresh run will start from scratch.

In [5]:
# ==========================================
# DATA LOADING + TRAIN / VALIDATION SPLITS
# ==========================================

try:
    CATEGORIES
except NameError:
    CATEGORIES = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]

# Keep variable names; only add safe defaults
candidate_train = ["train_cleaned_light.csv", "train.csv"]
train_path = next((p for p in candidate_train if os.path.exists(p)), "train.csv")
test_path = "test.csv" if os.path.exists("test.csv") else "/mnt/data/test.csv"
test_labels_path = "test_labels.csv" if os.path.exists("test_labels.csv") else "/mnt/data/test_labels.csv"

train_df = pd.read_csv(train_path, engine="python", on_bad_lines="skip")
test_df = pd.read_csv(test_path, engine="python", on_bad_lines="skip")
test_labels_df = pd.read_csv(test_labels_path, engine="python", on_bad_lines="skip")

print("Using train_path:", train_path)
print("Using test_path:", test_path)
print("Using test_labels_path:", test_labels_path)

print("train_df:", train_df.shape, train_df.columns.tolist())
print("test_df:", test_df.shape, test_df.columns.tolist())
print("test_labels_df:", test_labels_df.shape, test_labels_df.columns.tolist())

required_train_cols = ["comment_text"] + CATEGORIES
missing_train = [c for c in required_train_cols if c not in train_df.columns]
if missing_train:
    raise ValueError(f"train_df missing columns: {missing_train}")

required_test_cols = ["id", "comment_text"]
missing_test = [c for c in required_test_cols if c not in test_df.columns]
if missing_test:
    raise ValueError(f"test_df missing columns: {missing_test}")

required_label_cols = ["id"] + CATEGORIES
missing_labels = [c for c in required_label_cols if c not in test_labels_df.columns]
if missing_labels:
    raise ValueError(f"test_labels_df missing columns: {missing_labels}")

# Keep raw text for traceability, then create two views
for _df in (train_df, test_df):
    _df["comment_text_raw"] = _df["comment_text"].astype(str)
    _df["comment_text"] = _df["comment_text_raw"].apply(normalize_for_llm)       # used by LLM/reporting
    _df["comment_text_sparse"] = _df["comment_text_raw"].apply(normalize_for_sparse)  # used by TF-IDF baselines

scorable = test_labels_df["toxic"] != -1
test_eval_df = test_df.merge(test_labels_df[scorable], on="id", how="inner")

print("test_eval_df (scorable):", test_eval_df.shape)

# ---------
# Internal development splits (NO TEST LEAKAGE)
# train_fit_df  : fit TF-IDF baseline and provide a general training pool
# prompt_pool_df: source of curated few-shot examples only
# val_df        : validation set for threshold tuning only
# ---------
train_df = train_df.copy().reset_index(drop=True)
train_df["any_toxic"] = (train_df[CATEGORIES].sum(axis=1) > 0).astype(int)

train_fit_df, temp_df = train_test_split(
    train_df,
    test_size=0.10,
    random_state=SEED,
    stratify=train_df["any_toxic"]
)

prompt_pool_df, val_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=SEED,
    stratify=temp_df["any_toxic"]
)

for _df in (train_fit_df, prompt_pool_df, val_df, test_eval_df):
    if "any_toxic" in _df.columns:
        _df.drop(columns=["any_toxic"], inplace=True)

# Main held-out evaluation set (natural class distribution)
eval_n = min(EVAL_NATURAL_N, len(test_eval_df))
eval_subset = test_eval_df.sample(n=eval_n, random_state=SEED).reset_index(drop=True)

# Optional challenge / stress-test subset
def balanced_sample(df, categories, n_pos=200, n_neg=200, seed=None):
    if seed is None:
        seed = SEED

    idx = set()
    for cat in categories:
        pos_pool = df[df[cat] == 1]
        neg_pool = df[df[cat] == 0]
        if len(pos_pool) > 0:
            idx.update(pos_pool.sample(min(n_pos, len(pos_pool)), random_state=seed).index.tolist())
        if len(neg_pool) > 0:
            idx.update(neg_pool.sample(min(n_neg, len(neg_pool)), random_state=seed).index.tolist())

    return df.loc[list(idx)].sample(frac=1, random_state=seed).reset_index(drop=True)

challenge_subset = balanced_sample(test_eval_df, CATEGORIES, n_pos=CHALLENGE_N_POS, n_neg=CHALLENGE_N_NEG, seed=SEED)
val_pilot_df = balanced_sample(val_df, CATEGORIES, n_pos=120, n_neg=120, seed=SEED)

print("train_fit_df:", train_fit_df.shape)
print("prompt_pool_df:", prompt_pool_df.shape)
print("val_df:", val_df.shape)
print("eval_subset:", eval_subset.shape)
print("challenge_subset:", challenge_subset.shape)
print("val_pilot_df:", val_pilot_df.shape)

Using train_path: train_cleaned_light.csv
Using test_path: test.csv
Using test_labels_path: test_labels.csv
train_df: (159571, 8) ['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
test_df: (153164, 2) ['id', 'comment_text']
test_labels_df: (153164, 7) ['id', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
test_eval_df (scorable): (63978, 10)
train_fit_df: (143613, 10)
prompt_pool_df: (7979, 10)
val_df: (7979, 10)
eval_subset: (2000, 10)
challenge_subset: (2429, 10)
val_pilot_df: (1045, 10)

In [6]:
# ==========================================
# UTILITIES (KEEP VARIABLE NAMES)
# ==========================================

def safe_truncate(text, max_chars=MAX_CHARS):
    return text[:max_chars] if isinstance(text, str) else ""

def log_error(sample_id, raw_output, reason):
    error_log.append({
        "id": str(sample_id),
        "reason": reason,
        "raw_output": raw_output
    })

def labels_to_text(row_like):
    active = [c for c in CATEGORIES if int(row_like.get(c, 0)) == 1]
    return ", ".join(active) if active else "clean"

In [7]:
# ==========================================
# MULTI-LABEL + IMBALANCE DIAGNOSTICS
# ==========================================

def multilabel_diagnostics(df, name="dataset"):
    label_counts = df[CATEGORIES].sum().astype(int)
    prevalence = (label_counts / len(df)).sort_values(ascending=True)
    label_count_per_row = df[CATEGORIES].sum(axis=1)

    summary = pd.DataFrame({
        "label": prevalence.index,
        "positives": [int(label_counts[c]) for c in prevalence.index],
        "prevalence": [float(prevalence[c]) for c in prevalence.index],
        "rarity_rank": list(range(1, len(CATEGORIES) + 1))
    })

    overlap = pd.DataFrame({
        "rows": [len(df)],
        "clean_rows": [int((label_count_per_row == 0).sum())],
        "any_toxic_rows": [int((label_count_per_row > 0).sum())],
        "multi_label_rows": [int((label_count_per_row >= 2).sum())],
        "label_cardinality": [float(label_count_per_row.mean())],
        "label_density": [float(label_count_per_row.mean() / len(CATEGORIES))],
        "multi_label_rate_among_positive": [
            float((label_count_per_row >= 2).sum() / max((label_count_per_row > 0).sum(), 1))
        ],
    })

    print()
    print(f"{name.upper()} MULTI-LABEL / IMBALANCE DIAGNOSTICS")
    display(summary)
    display(overlap)
    return summary, overlap

prompt_pool_label_summary, prompt_pool_overlap = multilabel_diagnostics(prompt_pool_df, name="prompt_pool_df")
eval_label_summary, eval_overlap = multilabel_diagnostics(eval_subset, name="eval_subset")

# Rare labels are defined empirically from the prompt pool prevalence.
# This is what justifies deliberate few-shot coverage instead of random examples.
RARE_LABELS = prompt_pool_label_summary.sort_values("prevalence")["label"].head(3).tolist()
COMMON_LABELS = [c for c in CATEGORIES if c not in RARE_LABELS]
print("Rare labels in prompt_pool_df:", RARE_LABELS)
print("Commoner labels in prompt_pool_df:", COMMON_LABELS)

PROMPT_POOL_DF MULTI-LABEL / IMBALANCE DIAGNOSTICS

           label  positives  prevalence  rarity_rank
0         threat         18    0.002256            1
1   severe_toxic         67    0.008397            2
2  identity_hate         75    0.009400            3
3         insult        393    0.049254            4
4        obscene        403    0.050508            5
5          toxic        763    0.095626            6

,rows,clean_rows,any_toxic_rows,multi_label_rows,label_cardinality,label_density,multi_label_rate_among_positive
0,7979,7167,812,481,0.215441,0.035907,0.592365

EVAL_SUBSET MULTI-LABEL / IMBALANCE DIAGNOSTICS

           label  positives  prevalence  rarity_rank
0         threat          7      0.0035            1
1   severe_toxic         13      0.0065            2
2  identity_hate         27      0.0135            3
3         insult        121      0.0605            4
4        obscene        123      0.0615            5
5          toxic        201      0.1005            6

,rows,clean_rows,any_toxic_rows,multi_label_rows,label_cardinality,label_density,multi_label_rate_among_positive
0,2000,1795,205,145,0.246,0.041,0.707317

Rare labels in prompt_pool_df: ['threat', 'severe_toxic', 'identity_hate']
Commoner labels in prompt_pool_df: ['toxic', 'obscene', 'insult']

### Leakage audit

In [8]:
# ==========================================
# LEAKAGE AUDIT
# ==========================================

def _id_set(df):
    return set(df["id"].astype(str).tolist())

def leakage_audit(train_fit_df, prompt_pool_df, val_df, eval_subset, challenge_subset=None):
    sets = {
        "train_fit": _id_set(train_fit_df),
        "prompt_pool": _id_set(prompt_pool_df),
        "val": _id_set(val_df),
        "eval": _id_set(eval_subset),
    }
    if challenge_subset is not None:
        sets["challenge"] = _id_set(challenge_subset)

    names = list(sets.keys())
    clean = True
    print("Leakage audit:")
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            a, b = names[i], names[j]
            inter = sets[a] & sets[b]
            print(f"  {a} ∩ {b}: {len(inter)}")
            if len(inter) > 0:
                clean = False

    if clean:
        print("PASS: no overlapping IDs across declared splits.")
    else:
        print("WARNING: overlapping IDs found. Investigate before reporting final results.")

leakage_audit(train_fit_df, prompt_pool_df, val_df, eval_subset, challenge_subset)

Leakage audit:
  train_fit ∩ prompt_pool: 0
  train_fit ∩ val: 0
  train_fit ∩ eval: 0
  train_fit ∩ challenge: 0
  prompt_pool ∩ val: 0
  prompt_pool ∩ eval: 0
  prompt_pool ∩ challenge: 0
  val ∩ eval: 0
  val ∩ challenge: 0
  eval ∩ challenge: 66
WARNING: overlapping IDs found. Investigate before reporting final results.

### Why the notebook uses curated few-shot examples

The code above computes label prevalence and overlap because the task is **multi-label** and **imbalanced**. Recent journal work notes that multi-label text classification is harder than single-label classification because of **label correlations** and **label data imbalance**, especially for rarer labels. A curated few-shot bank is therefore used instead of random demonstrations so the prompt can include: (i) a clean non-toxic case, (ii) boundary-focused cases, (iii) rare-label cases, and (iv) at least one multi-label case. This is also consistent with official prompt-engineering guidance that recommends few-shot prompting and structured outputs when the task rubric is hard to infer and reliable schema-constrained outputs are needed.

References: Yuan et al. (2024), *Scientific Reports*, on multi-label text classification challenges from label correlations and imbalance; OpenAI Prompt Engineering and Structured Outputs guides on few-shot prompting and fixed-schema outputs.

### Why the curated few-shot bank is justified
The diagnostics above are computed directly from the data and show two properties that matter for prompt design:

1. **Multi-label overlap**: some comments activate more than one toxicity label, so the prompt needs at least one example where labels co-occur.
2. **Class imbalance**: rarer labels such as the least-prevalent classes in `prompt_pool_df` should not be left to random example selection.

The code below therefore builds a **curated** few-shot bank with a clean case, contrastive boundary cases, rare-label cases, and one multi-label case.

In [9]:

# ==========================================
# CURATED FEW-SHOT EXAMPLES
# ==========================================

# Why curated few-shot?
# 1) This task is multi-label: one comment can activate multiple labels at once.
# 2) The label distribution is imbalanced: rare labels should not be left to random sampling.
# 3) Some labels have overlapping boundaries (e.g. obscene vs insult; toxic vs severe_toxic).
# 4) For precision-sensitive labels, include one near-miss example so the model sees what should remain 0.
# Therefore the prompt examples are selected deliberately rather than randomly.

def describe_labels(row):
    return {c: int(row[c]) for c in CATEGORIES}

def _rank_examples(pool):
    if len(pool) == 0:
        return pool

    rarity_weights = {label: (len(CATEGORIES) - rank) for rank, label in enumerate(RARE_LABELS)}
    rarity_score = sum(rarity_weights.get(c, 0) * pool[c] for c in CATEGORIES)

    return pool.assign(
        _label_count=pool[CATEGORIES].sum(axis=1),
        _text_len=pool["comment_text"].fillna("").astype(str).str.len(),
        _rarity_score=rarity_score,
        _boundary_bonus=(pool["obscene"] + pool["insult"] + pool["severe_toxic"])
    ).sort_values(
        ["_rarity_score", "_label_count", "_boundary_bonus", "_text_len"],
        ascending=[False, False, False, True]
    )

def select_example(df, used_ids, required=None, forbidden=None, min_labels=None, max_labels=None):
    required = required or {}
    forbidden = forbidden or {}

    pool = df.copy()
    pool = pool[~pool["id"].astype(str).isin(used_ids)]

    for c, v in required.items():
        pool = pool[pool[c] == v]
    for c, v in forbidden.items():
        pool = pool[pool[c] != v]

    if min_labels is not None:
        pool = pool[pool[CATEGORIES].sum(axis=1) >= min_labels]
    if max_labels is not None:
        pool = pool[pool[CATEGORIES].sum(axis=1) <= max_labels]

    ranked = _rank_examples(pool)
    if len(ranked) == 0:
        return None
    return ranked.iloc[0]

def build_curated_fewshot_bank(prompt_pool_df, variant="precision_8"):
    used_ids = set()

    slot_map = {
        "contrastive_7": [
            ("clean", {"required": {c: 0 for c in CATEGORIES}, "max_labels": 0}),
            ("obscene_focus", {"required": {"obscene": 1, "insult": 0, "identity_hate": 0, "threat": 0}, "forbidden": {"severe_toxic": 1}, "min_labels": 1}),
            ("insult_focus", {"required": {"insult": 1, "identity_hate": 0, "threat": 0}, "forbidden": {"severe_toxic": 1}, "min_labels": 1}),
            ("identity_hate", {"required": {"identity_hate": 1}, "min_labels": 1}),
            ("threat", {"required": {"threat": 1}, "min_labels": 1}),
            ("severe_toxic", {"required": {"severe_toxic": 1}, "min_labels": 1}),
            ("multi_label", {"min_labels": 2}),
        ],
        "precision_8": [
            ("clean", {"required": {c: 0 for c in CATEGORIES}, "max_labels": 0}),
            ("near_miss_non_threat", {"required": {"threat": 0, "identity_hate": 0, "severe_toxic": 0}, "forbidden": {"toxic": 0, "obscene": 0, "insult": 0}, "min_labels": 1, "max_labels": 2}),
            ("obscene_focus", {"required": {"obscene": 1, "insult": 0, "identity_hate": 0, "threat": 0}, "forbidden": {"severe_toxic": 1}, "min_labels": 1, "max_labels": 2}),
            ("insult_focus", {"required": {"insult": 1, "identity_hate": 0, "threat": 0}, "forbidden": {"severe_toxic": 1}, "min_labels": 1, "max_labels": 2}),
            ("identity_hate", {"required": {"identity_hate": 1}, "min_labels": 1}),
            ("threat", {"required": {"threat": 1}, "min_labels": 1}),
            ("severe_toxic", {"required": {"severe_toxic": 1}, "min_labels": 1}),
            ("multi_label", {"min_labels": 2}),
        ],
        "balanced_8": [
            ("clean", {"required": {c: 0 for c in CATEGORIES}, "max_labels": 0}),
            ("toxic", {"required": {"toxic": 1}, "min_labels": 1}),
            ("obscene", {"required": {"obscene": 1}, "min_labels": 1}),
            ("insult", {"required": {"insult": 1}, "min_labels": 1}),
            ("identity_hate", {"required": {"identity_hate": 1}, "min_labels": 1}),
            ("threat", {"required": {"threat": 1}, "min_labels": 1}),
            ("severe_toxic", {"required": {"severe_toxic": 1}, "min_labels": 1}),
            ("multi_label", {"min_labels": 2}),
        ],
    }

    slots = slot_map.get(variant, slot_map["precision_8"])
    bank = []
    for slot_name, rules in slots:
        row = select_example(prompt_pool_df, used_ids, **rules)
        if row is None:
            continue
        used_ids.add(str(row["id"]))
        bank.append({
            "slot": slot_name,
            "id": str(row["id"]),
            "comment_text": safe_truncate(str(row["comment_text"])),
            "labels": describe_labels(row)
        })
    return bank

fewshot_bank = build_curated_fewshot_bank(prompt_pool_df, variant=FEWSHOT_VARIANT)
print("Curated few-shot bank size:", len(fewshot_bank))
display(pd.DataFrame([{"slot": ex["slot"], "id": ex["id"], **ex["labels"]} for ex in fewshot_bank]))

def build_examples_block_curated():
    blocks = []
    for ex in fewshot_bank:
        blocks.append(
            "Example:\n"
            f"Comment: {json.dumps(ex['comment_text'])}\n"
            f"Labels: {json.dumps(ex['labels'])}"
        )
    return "\n\n".join(blocks)

Curated few-shot bank size: 7

,slot,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,clean,adac7518742a67c6,0,0,0,0,0,0
1,obscene_focus,db082dda6e9577b9,1,0,1,0,0,0
2,insult_focus,532ed50c0bb94f95,0,0,1,0,1,0
3,identity_hate,7ba7b175e597c13e,1,1,1,1,1,1
4,threat,66c3bced1735cb90,1,1,1,1,1,1
5,severe_toxic,dd971e65a617c67e,1,1,1,1,1,0
6,multi_label,82b5aed7526148df,1,1,1,1,1,0

In [10]:
# ==========================================
# PROMPT
# ==========================================

def build_prompt(text, train_df=None, mode="few-shot"):
    definitions = (
        "Label definitions:\n"
        "- toxic: rude, hostile, or disrespectful language toward a person or group. Broad category.\n"
        "- severe_toxic: extreme abuse, dehumanising language, intense hate speech, or unusually violent/graphic toxicity. If severe_toxic=1 then toxic should also be 1.\n"
        "- obscene: vulgar, profane, or sexually explicit offensive wording.\n"
        "- threat: explicit threat, wish of harm, or credible violent intent. Default to 0 unless harm is clear.\n"
        "- insult: direct personal attack, demeaning language, or name-calling aimed at a person or group.\n"
        "- identity_hate: attack directed at a protected or social identity group such as race, religion, nationality, gender, disability, or sexual orientation.\n"
    )

    decision_rules = (
        "Decision rules:\n"
        "1. This is MULTI-LABEL classification: multiple labels can be 1 at the same time.\n"
        "2. Assign 1 only when there is clear evidence for that label; otherwise assign 0. When uncertain, prefer 0.\n"
        "3. Profanity alone may justify obscene, but does not always imply insult, toxic, or identity_hate.\n"
        "4. Threat should be 1 only when there is a genuine threat or clear wish of harm/violence.\n"
        "5. Identity_hate should be 1 only when the attack targets a group identity, not just an individual.\n"
        "6. severe_toxic is much stricter than toxic: ordinary abuse or profanity is NOT enough. severe_toxic requires extreme abuse, dehumanising language, or unusually violent/graphic hostility.\n"
        "7. Do not infer threat from anger or profanity alone; threat requires an explicit threat or clear wish of physical harm.\n"
        "8. Do not infer identity_hate unless the attack clearly targets an identity group.\n"
        "9. Return STRICT JSON only with integer 0/1 values and include all six labels.\n"
        "7. The few-shot examples were curated because the task is imbalanced and multi-label: they include a clean case, rare-label cases, and a multi-label case.\n"
        "8. Return STRICT JSON only with integer 0/1 values and include all six labels.\n"
    )

    output_format = (
        'Return ONLY this JSON shape:\n'
        '{"toxic": 0, "severe_toxic": 0, "obscene": 0, "threat": 0, "insult": 0, "identity_hate": 0}'
    )

    prompt_parts = [
        "You are an expert content moderation classifier.",
        definitions,
        decision_rules,
    ]

    if mode == "few-shot":
        prompt_parts.append("Few-shot examples:\n" + build_examples_block_curated())

    prompt_parts.extend([
        "Classify this comment:",
        json.dumps(safe_truncate(text)),
        output_format
    ])

    return "\n\n".join(prompt_parts)

def build_severe_recheck_prompt(text, base_labels):
    return "\n\n".join([
        "You are reviewing ONLY the label severe_toxic for a moderation system.",
        "Question: Should severe_toxic be 1 for this comment?",
        "Use a STRICT standard. severe_toxic=1 only for extreme abuse, dehumanising language, explicit sadistic or violent hostility, or unusually graphic toxic content.",
        "Ordinary toxicity, insults, or profanity alone are NOT enough for severe_toxic.",
        f"Base labels already predicted: {json.dumps({k:int(base_labels.get(k,0)) for k in CATEGORIES if k != 'severe_toxic'})}",
        f"Comment: {json.dumps(safe_truncate(text))}",
        'Return ONLY JSON: {"severe_toxic": 0}'
    ])

### Reference-backed choices used in this notebook

- **Dataset / task:** Jigsaw Toxic Comment Classification Challenge (Kaggle official).
- **Structured JSON outputs for the LLM path:** OpenAI Structured Outputs / JSON output guidance.
- **Traditional baseline:** TF-IDF + One-vs-Rest Logistic Regression as a strong, interpretable text-classification baseline.
- **Evaluation design:** a 2,000-row natural held-out set for the main comparison, with the challenge subset kept only as optional secondary stress testing.

These choices are reflected in the report recommendations and final write-up.

### Optional prompt-validation pilot
Use `val_pilot_df` first to compare zero-shot vs few-shot on a smaller validation sample before running the full 1,000-comment held-out test.

In [11]:
# Optional validation pilot is controlled by RUN_VALIDATION_PILOT in the config cell.
print(f"FEWSHOT_VARIANT={FEWSHOT_VARIANT}")
print(f"RUN_VALIDATION_PILOT={RUN_VALIDATION_PILOT}")
print(f"RUN_CHALLENGE_EVAL={RUN_CHALLENGE_EVAL}")

FEWSHOT_VARIANT=precision_8
RUN_VALIDATION_PILOT=False
RUN_CHALLENGE_EVAL=False

In [12]:

# ==========================================
# MODEL CALL
# ==========================================

def get_completion(prompt, sample_id=None, row_num=None, total=None):
    for attempt in range(RETRIES):
        try:
            time.sleep(REQUEST_DELAY)
            if attempt == 0 and row_num is not None and total is not None and sample_id is not None:
                print(f"Requesting row {row_num}/{total} | id={sample_id}")

            kwargs = dict(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                timeout=90,
            )
            if USE_JSON_MODE:
                kwargs["response_format"] = {"type": "json_object"}

            res = client.chat.completions.create(**kwargs)
            return res.choices[0].message.content

        except Exception as e:
            msg = f"Attempt {attempt+1}/{RETRIES} failed"
            if sample_id is not None:
                msg += f" for id={sample_id}"
            msg += f": {e}"
            print(msg)
            time.sleep(2 ** attempt)

    return None

In [13]:
# ==========================================
# OUTPUT PARSING
# ==========================================

def _coerce01(v):
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, (int, np.integer)):
        return 1 if int(v) == 1 else 0
    if isinstance(v, float):
        return 1 if abs(v - 1.0) < 1e-9 else 0
    if isinstance(v, str):
        s = v.strip().lower()
        if s in {"1", "true", "yes"}:
            return 1
        if s in {"0", "false", "no", ""}:
            return 0
    return None

def parse_output(raw, sample_id):

    if not raw:
        log_error(sample_id, raw, "EMPTY_RESPONSE")
        return None

    try:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            log_error(sample_id, raw, "NO_JSON_OBJECT_FOUND")
            return None

        data = json.loads(match.group())
        out = {}
        for c in CATEGORIES:
            v = _coerce01(data.get(c, 0))
            if v is None:
                log_error(sample_id, raw, f"BAD_VALUE_{c}")
                return None
            out[c] = int(v)
        return out

    except Exception:
        log_error(sample_id, raw, "JSON_PARSE_ERROR")
        return None

In [14]:

# ==========================================
# BATCH INFERENCE WITH CHECKPOINTING / RESUME
# ==========================================

def maybe_recheck_severe(text, parsed, sample_id=None, mode="zero-shot"):
    if not SEVERE_RECHECK or mode not in SEVERE_RECHECK_MODES:
        return parsed, None

    trigger = any(int(parsed.get(c, 0)) == 1 for c in ["toxic", "obscene", "insult", "identity_hate", "threat"])
    if not trigger:
        return parsed, None

    prompt = build_severe_recheck_prompt(text, parsed)
    raw = get_completion(prompt, sample_id=sample_id)
    rechecked = parse_output(raw, sample_id)
    if isinstance(rechecked, dict) and "severe_toxic" in rechecked:
        parsed["severe_toxic"] = int(rechecked["severe_toxic"])
    return parsed, raw


def run_inference(df, mode="zero-shot", out_prefix="run", resume=RESUME_RUN):
    global error_log
    error_log = []

    pred_path = f"{out_prefix}_{mode}_preds.csv"
    raw_path = f"{out_prefix}_{mode}_raw.csv"
    err_path = f"{out_prefix}_{mode}_errors.csv"

    preds = []
    raw_outs = []
    done_ids = set()

    if resume and os.path.exists(pred_path):
        existing_preds = pd.read_csv(pred_path)
        if "id" in existing_preds.columns:
            preds = existing_preds.to_dict("records")
            done_ids = set(existing_preds["id"].astype(str))
            print(f"Resuming {mode}: found {len(done_ids)} completed predictions in {pred_path}")

    if resume and os.path.exists(raw_path):
        existing_raw = pd.read_csv(raw_path)
        raw_outs = existing_raw.to_dict("records")

    if resume and os.path.exists(err_path):
        existing_err = pd.read_csv(err_path)
        error_log = existing_err.to_dict("records")

    work_df = df.copy()
    work_df["id"] = work_df["id"].astype(str)

    total = len(work_df)
    start_ts = time.time()
    processed_this_run = 0
    print(f"Starting {mode} inference on {total} rows | resume={resume} | checkpoint every {SAVE_EVERY} rows | prefix={out_prefix}")

    for j, row in enumerate(work_df.itertuples(index=False), start=1):
        sample_id = str(row.id)
        text = getattr(row, LLM_TEXT_COL)

        if sample_id in done_ids:
            if j % PROGRESS_EVERY == 0 or j == total:
                print(f"{mode}: scanned {j}/{total} rows | existing_completed={len(done_ids)} | current_run_done={processed_this_run}")
            continue

        prompt = build_prompt(text, mode=mode)
        raw = get_completion(prompt, sample_id=sample_id, row_num=j, total=total)

        parsed = parse_output(raw, sample_id)
        if parsed is None:
            parsed = {c: 0 for c in CATEGORIES}

        severe_raw = None
        parsed, severe_raw = maybe_recheck_severe(text, parsed, sample_id=sample_id, mode=mode)

        raw_outs.append({"id": sample_id, "raw": raw, "severe_recheck_raw": severe_raw})

        parsed["id"] = sample_id
        preds.append(parsed)
        done_ids.add(sample_id)
        processed_this_run += 1

        elapsed = time.time() - start_ts
        rate = processed_this_run / elapsed if elapsed > 0 else 0.0
        if processed_this_run % PROGRESS_EVERY == 0 or j == total:
            print(
                f"{mode}: completed {len(done_ids)}/{total} total | new this run={processed_this_run} | "
                f"elapsed={elapsed/60:.1f} min | speed={rate:.2f} new rows/sec"
            )

        if len(done_ids) % SAVE_EVERY == 0:
            pd.DataFrame(preds).to_csv(pred_path, index=False)
            pd.DataFrame(raw_outs).to_csv(raw_path, index=False)
            if error_log:
                pd.DataFrame(error_log).to_csv(err_path, index=False)
            print(f"{mode}: saved checkpoint at {len(done_ids)}/{total} rows -> {pred_path}")

    pred_df = pd.DataFrame(preds)
    raw_df = pd.DataFrame(raw_outs)

    pred_df.to_csv(pred_path, index=False)
    raw_df.to_csv(raw_path, index=False)

    if error_log:
        pd.DataFrame(error_log).to_csv(err_path, index=False)

    elapsed = time.time() - start_ts
    print(f"Finished {mode}: {len(done_ids)}/{total} rows saved | elapsed={elapsed/60:.1f} min")
    return pred_df.sort_values("id").reset_index(drop=True)

### LLM INFERENCE

In [ ]:

# Optional cheaper validation pass before the full held-out run.
if RUN_VALIDATION_PILOT:
    print("Running validation pilot first...")
    val_zero_preds = run_inference(val_pilot_df, mode="zero-shot", out_prefix=f"{SAVE_PREFIX}_valpilot", resume=RESUME_RUN)
    val_few_preds  = run_inference(val_pilot_df, mode="few-shot",  out_prefix=f"{SAVE_PREFIX}_valpilot", resume=RESUME_RUN)
    _ = evaluate_preds(val_zero_preds, val_pilot_df, name="Validation Zero-shot")
    _ = evaluate_preds(val_few_preds,  val_pilot_df, name="Validation Few-shot")

print(f"Running full {len(eval_subset)}-sample held-out evaluation...")
zero_preds = run_inference(eval_subset, mode="zero-shot", out_prefix=SAVE_PREFIX, resume=RESUME_RUN)
few_preds  = run_inference(eval_subset, mode="few-shot",  out_prefix=SAVE_PREFIX, resume=RESUME_RUN)

Running full 2000-sample held-out evaluation...
Starting zero-shot inference on 2000 rows | resume=False | checkpoint every 50 rows | prefix=eval2000_gpt-4_1_lightprep
Requesting row 1/2000 | id=cbd83ffa0927bc8d
Requesting row 2/2000 | id=9fea96fb811c62aa
Requesting row 3/2000 | id=00978e3b8f542b9b
Requesting row 4/2000 | id=8bc68561a51e6ed7
Requesting row 5/2000 | id=6b1e3a100ce58634
Requesting row 6/2000 | id=ae647b958fdc9dc6
Requesting row 7/2000 | id=8e03374282aa3f89
Requesting row 8/2000 | id=6bcdc3a6c203e3c7
Requesting row 9/2000 | id=dcef1f24585ba512
Requesting row 10/2000 | id=fc81f49865426fc6
zero-shot: completed 10/2000 total | new this run=10 | elapsed=0.2 min | speed=0.70 new rows/sec
Requesting row 11/2000 | id=1f9259f23eb5d7cb
Requesting row 12/2000 | id=e0781d98e6e69d86
Requesting row 13/2000 | id=61c14a3ec5909487
Requesting row 14/2000 | id=7eb070a5952c2253
Requesting row 15/2000 | id=88125237fc6fec1c
Requesting row 16/2000 | id=244693b0bfde36c1
Requesting row 17/2000 | id=683d889fe5e3377c
Requesting row 18/2000 | id=3a25f9ee8acb7a29
Requesting row 19/2000 | id=8416155aba0a1286
Requesting row 20/2000 | id=abb9b990a9d125f5
zero-shot: completed 20/2000 total | new this run=20 | elapsed=0.4 min | speed=0.76 new rows/sec
Requesting row 21/2000 | id=be00383724970b30
Requesting row 22/2000 | id=53c35126f04282e3
Requesting row 23/2000 | id=f697b741f889f8c1
Requesting row 24/2000 | id=cccfaae9e03529fc
Requesting row 25/2000 | id=1c04f1a1a03e0672
Requesting row 26/2000 | id=647ac23da7a221f8
Requesting row 27/2000 | id=4789dc7de84b3a8a
Requesting row 28/2000 | id=e77b537d51e5c3ac
Requesting row 29/2000 | id=761c12df85f861eb
Requesting row 30/2000 | id=10c04c45556782e1
zero-shot: completed 30/2000 total | new this run=30 | elapsed=0.6 min | speed=0.79 new rows/sec
Requesting row 31/2000 | id=899956b1be1fd934
Requesting row 32/2000 | id=4da4c74427869b6f
Requesting row 33/2000 | id=435d74e45684f689
Requesting row 34/2000 | id=b0027542948a578d
Requesting row 35/2000 | id=db98103b5c1c9625
Requesting row 36/2000 | id=0a780c9878fa8726
Requesting row 37/2000 | id=5a497bb254213d2d
Requesting row 38/2000 | id=fd71f27e8cf2c111
Requesting row 39/2000 | id=bbce36839ad3da14
Requesting row 40/2000 | id=aa6f3ae40203b106
zero-shot: completed 40/2000 total | new this run=40 | elapsed=0.8 min | speed=0.81 new rows/sec
Requesting row 41/2000 | id=7932911a2d30f577
Requesting row 42/2000 | id=e6ba8a3bee1c72db
Requesting row 43/2000 | id=3c55ad4dcdbc06e2
Requesting row 44/2000 | id=50534481cf36083d
Requesting row 45/2000 | id=0c74ec21d528e7dc
Requesting row 46/2000 | id=f29cc2cee3b3f350
Requesting row 47/2000 | id=9e54982c509607e0
Requesting row 48/2000 | id=400642d51228065b

In [ ]:
# ==========================================
# EVALUATION (multi-label)
# ==========================================

def per_class_metrics_df(y_true, y_pred):
    rows = []
    for i, c in enumerate(CATEGORIES):
        yt = y_true[:, i]
        yp = y_pred[:, i]
        tp = int(((yt == 1) & (yp == 1)).sum())
        fp = int(((yt == 0) & (yp == 1)).sum())
        fn = int(((yt == 1) & (yp == 0)).sum())
        tn = int(((yt == 0) & (yp == 0)).sum())

        prec = precision_score(yt, yp, zero_division=0)
        rec = recall_score(yt, yp, zero_division=0)
        f1 = f1_score(yt, yp, zero_division=0)
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0

        rows.append({
            "label": c,
            "precision": prec,
            "recall": rec,
            "f1": f1,
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "tn": tn,
            "support": int(yt.sum()),
            "false_positive_rate": fpr,
            "precision_priority": c in PRECISION_PRIORITY_LABELS
        })
    return pd.DataFrame(rows)


def evaluate_preds(pred_df, true_df, name="model", return_details=False):
    merged = pred_df.merge(
        true_df[["id", "comment_text"] + CATEGORIES],
        on="id",
        how="inner",
        suffixes=("_pred", "_true")
    )

    y_true = merged[[f"{c}_true" for c in CATEGORIES]].values
    y_pred = merged[[f"{c}_pred" for c in CATEGORIES]].values

    metrics = {
        "name": name,
        "micro_precision": precision_score(y_true, y_pred, average="micro", zero_division=0),
        "micro_recall": recall_score(y_true, y_pred, average="micro", zero_division=0),
        "micro_f1": f1_score(y_true, y_pred, average="micro", zero_division=0),
        "macro_precision": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "macro_recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "macro_f1": f1_score(y_true, y_pred, average="macro", zero_division=0),
        "subset_accuracy": accuracy_score(y_true, y_pred),
        "hamming_loss": hamming_loss(y_true, y_pred),
        "jaccard_macro": jaccard_score(y_true, y_pred, average="macro", zero_division=0),
        "jaccard_samples": jaccard_score(y_true, y_pred, average="samples", zero_division=0),
        "n_rows": len(merged),
    }

    class_df = per_class_metrics_df(y_true, y_pred)

    print(f"\n===== {name} =====")
    print(f"Micro  Prec={metrics['micro_precision']:.4f}  Rec={metrics['micro_recall']:.4f}  F1={metrics['micro_f1']:.4f}")
    print(f"Macro  Prec={metrics['macro_precision']:.4f}  Rec={metrics['macro_recall']:.4f}  F1={metrics['macro_f1']:.4f}")
    print(f"Subset (Exact-Match) Accuracy: {metrics['subset_accuracy']:.4f}")
    print(f"Hamming Loss: {metrics['hamming_loss']:.4f}")
    print(f"Jaccard (macro): {metrics['jaccard_macro']:.4f}")
    print(f"Jaccard (samples): {metrics['jaccard_samples']:.4f}")
    print("\nPer-class report:")
    display(class_df.sort_values(['f1', 'support'], ascending=[False, False]).reset_index(drop=True))

    if return_details:
        return metrics, class_df, merged
    return metrics

In [ ]:
# ==========================================
# ERROR ANALYSIS
# ==========================================

def extract_error_cases(pred_df, true_df):

    merged = pred_df.merge(
        true_df[["id","comment_text"] + CATEGORIES],
        on="id",
        suffixes=("_pred","_true")
    )

    mask = pd.Series(False, index=merged.index)

    for c in CATEGORIES:
        mask |= (merged[c+"_pred"] != merged[c+"_true"])

    return merged[mask]

In [ ]:
# ==========================================
# BASELINES
# ==========================================

def all_zero_baseline(true_df, name="Baseline: All-zero"):
    pred = pd.DataFrame({"id": true_df["id"]})
    for c in CATEGORIES:
        pred[c] = 0
    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred


def tune_thresholds_on_validation(score_arr, y_val, grid=None, is_probability=True):
    if grid is None:
        grid = np.arange(0.10, 0.91, 0.05) if is_probability else np.arange(-1.5, 1.51, 0.10)

    thresholds = {}
    for j, c in enumerate(CATEGORIES):
        best_t = 0.50 if is_probability else 0.0
        best_f1 = -1.0
        for t in grid:
            pred = (score_arr[:, j] >= t).astype(int)
            score = f1_score(y_val[:, j], pred, zero_division=0)
            if score > best_f1:
                best_f1 = score
                best_t = float(t)
        thresholds[c] = best_t
    return thresholds


def build_word_tfidf(train_fit_df, val_df, true_df):
    X_train = train_fit_df[SPARSE_TEXT_COL].fillna("").astype(str).values
    Y_train = train_fit_df[CATEGORIES].values
    X_val = val_df[SPARSE_TEXT_COL].fillna("").astype(str).values
    Y_val = val_df[CATEGORIES].values
    X_test = true_df[SPARSE_TEXT_COL].fillna("").astype(str).values

    vec = TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=2,
        max_features=200000,
        sublinear_tf=True
    )
    Xtr = vec.fit_transform(X_train)
    Xva = vec.transform(X_val)
    Xte = vec.transform(X_test)
    return Xtr, Y_train, Xva, Y_val, Xte


def build_wordchar_tfidf(train_fit_df, val_df, true_df):
    X_train = train_fit_df[SPARSE_TEXT_COL].fillna("").astype(str).values
    Y_train = train_fit_df[CATEGORIES].values
    X_val = val_df[SPARSE_TEXT_COL].fillna("").astype(str).values
    Y_val = val_df[CATEGORIES].values
    X_test = true_df[SPARSE_TEXT_COL].fillna("").astype(str).values

    word_vec = TfidfVectorizer(
        analyzer="word",
        ngram_range=(1, 2),
        min_df=2,
        max_features=160000,
        sublinear_tf=True
    )
    char_vec = TfidfVectorizer(
        analyzer="char_wb",
        ngram_range=(3, 5),
        min_df=2,
        max_features=80000,
        sublinear_tf=True
    )

    Xtr_word = word_vec.fit_transform(X_train)
    Xva_word = word_vec.transform(X_val)
    Xte_word = word_vec.transform(X_test)

    Xtr_char = char_vec.fit_transform(X_train)
    Xva_char = char_vec.transform(X_val)
    Xte_char = char_vec.transform(X_test)

    Xtr = hstack([Xtr_word, Xtr_char]).tocsr()
    Xva = hstack([Xva_word, Xva_char]).tocsr()
    Xte = hstack([Xte_word, Xte_char]).tocsr()
    return Xtr, Y_train, Xva, Y_val, Xte


def tfidf_logreg_baseline(train_fit_df, val_df, true_df, name="Baseline: TFIDF+LogReg (tuned)"):
    Xtr, Ytr, Xva, Yva, Xte = build_word_tfidf(train_fit_df, val_df, true_df)

    clf = OneVsRestClassifier(LogisticRegression(max_iter=2000, class_weight="balanced"))
    clf.fit(Xtr, Ytr)

    val_proba = clf.predict_proba(Xva)
    thresholds = tune_thresholds_on_validation(val_proba, Yva, is_probability=True)
    test_proba = clf.predict_proba(Xte)

    pred = pd.DataFrame({"id": true_df["id"]})
    for j, c in enumerate(CATEGORIES):
        pred[c] = (test_proba[:, j] >= thresholds[c]).astype(int)

    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred, thresholds


def tfidf_linearsvm_baseline(train_fit_df, val_df, true_df, name="Baseline: TFIDF+LinearSVM (tuned)"):
    Xtr, Ytr, Xva, Yva, Xte = build_word_tfidf(train_fit_df, val_df, true_df)

    clf = OneVsRestClassifier(LinearSVC(C=1.0, class_weight="balanced", max_iter=5000))
    clf.fit(Xtr, Ytr)

    val_scores = clf.decision_function(Xva)
    thresholds = tune_thresholds_on_validation(val_scores, Yva, is_probability=False)
    test_scores = clf.decision_function(Xte)

    pred = pd.DataFrame({"id": true_df["id"]})
    for j, c in enumerate(CATEGORIES):
        pred[c] = (test_scores[:, j] >= thresholds[c]).astype(int)

    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred, thresholds


def wordchar_logreg_baseline(train_fit_df, val_df, true_df, name="Baseline: WordCharTFIDF+LogReg (tuned)"):
    Xtr, Ytr, Xva, Yva, Xte = build_wordchar_tfidf(train_fit_df, val_df, true_df)

    clf = OneVsRestClassifier(LogisticRegression(max_iter=2000, class_weight="balanced"))
    clf.fit(Xtr, Ytr)

    val_proba = clf.predict_proba(Xva)
    thresholds = tune_thresholds_on_validation(val_proba, Yva, is_probability=True)
    test_proba = clf.predict_proba(Xte)

    pred = pd.DataFrame({"id": true_df["id"]})
    for j, c in enumerate(CATEGORIES):
        pred[c] = (test_proba[:, j] >= thresholds[c]).astype(int)

    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred, thresholds




def wordchar_linearsvm_baseline(train_fit_df, val_df, true_df, name="Baseline: WordCharTFIDF+LinearSVM (tuned)"):
    Xtr, Ytr, Xva, Yva, Xte = build_wordchar_tfidf(train_fit_df, val_df, true_df)

    clf = OneVsRestClassifier(LinearSVC(C=1.0, class_weight="balanced", max_iter=5000))
    clf.fit(Xtr, Ytr)

    val_scores = clf.decision_function(Xva)
    thresholds = tune_thresholds_on_validation(val_scores, Yva, is_probability=False)
    test_scores = clf.decision_function(Xte)

    pred = pd.DataFrame({"id": true_df["id"]})
    for j, c in enumerate(CATEGORIES):
        pred[c] = (test_scores[:, j] >= thresholds[c]).astype(int)

    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred, thresholds

def classifier_chain_baseline(train_fit_df, val_df, true_df, name="Baseline: ClassifierChain+LogReg (tuned)"):
    Xtr, Ytr, Xva, Yva, Xte = build_word_tfidf(train_fit_df, val_df, true_df)

    base = LogisticRegression(max_iter=2000, class_weight="balanced")
    clf = ClassifierChain(base, order='random', random_state=SEED)
    clf.fit(Xtr, Ytr)

    val_proba = clf.predict_proba(Xva)
    thresholds = tune_thresholds_on_validation(val_proba, Yva, is_probability=True)
    test_proba = clf.predict_proba(Xte)

    pred = pd.DataFrame({"id": true_df["id"]})
    for j, c in enumerate(CATEGORIES):
        pred[c] = (test_proba[:, j] >= thresholds[c]).astype(int)

    result, class_df, merged = evaluate_preds(pred, true_df, name=name, return_details=True)
    return result, class_df, merged, pred, thresholds


zero_base_metrics, zero_base_class_df, zero_base_merged, zero_base_pred = all_zero_baseline(eval_subset)
lr_base_metrics, lr_base_class_df, lr_base_merged, lr_base_pred, lr_thresholds = tfidf_logreg_baseline(train_fit_df, val_df, eval_subset)
svm_metrics, svm_class_df, svm_merged, svm_pred, svm_thresholds = tfidf_linearsvm_baseline(train_fit_df, val_df, eval_subset)
wc_lr_metrics, wc_lr_class_df, wc_lr_merged, wc_lr_pred, wc_lr_thresholds = wordchar_logreg_baseline(train_fit_df, val_df, eval_subset)
wc_svm_metrics, wc_svm_class_df, wc_svm_merged, wc_svm_pred, wc_svm_thresholds = wordchar_linearsvm_baseline(train_fit_df, val_df, eval_subset)
cc_metrics, cc_class_df, cc_merged, cc_pred, cc_thresholds = classifier_chain_baseline(train_fit_df, val_df, eval_subset)

print("\nTuned logistic-regression thresholds:")
print(lr_thresholds)
print("\nTuned LinearSVM thresholds:")
print(svm_thresholds)
print("\nTuned Word+Char LogReg thresholds:")
print(wc_lr_thresholds)
print("\nTuned Word+Char LinearSVM thresholds:")
print(wc_svm_thresholds)
print("\nTuned ClassifierChain thresholds:")
print(cc_thresholds)

In [ ]:
# ==========================================
# MAIN EVALUATION RESULTS
# ==========================================

zero_metrics, zero_class_df, zero_merged = evaluate_preds(
    zero_preds,
    eval_subset,
    name="LLM Zero-shot",
    return_details=True
)

few_metrics, few_class_df, few_merged = evaluate_preds(
    few_preds,
    eval_subset,
    name="LLM Few-shot",
    return_details=True
)

print("Zero-shot and few-shot metrics created successfully.")

In [ ]:
# ==========================================
# BOOTSTRAP CONFIDENCE INTERVALS + TIDY REPORTING
# ==========================================

from datetime import datetime

# Ensure required metric objects exist
if "zero_metrics" not in globals():
    zero_metrics, zero_class_df, zero_merged = evaluate_preds(zero_preds, eval_subset, name="LLM Zero-shot", return_details=True)
if "few_metrics" not in globals():
    few_metrics, few_class_df, few_merged = evaluate_preds(few_preds, eval_subset, name="LLM Few-shot", return_details=True)
if "zero_base_metrics" not in globals():
    zero_base_metrics, zero_base_class_df, zero_base_merged, zero_base_pred = all_zero_baseline(eval_subset)
if "lr_base_metrics" not in globals():
    lr_base_metrics, lr_base_class_df, lr_base_merged, lr_base_pred, lr_thresholds = tfidf_logreg_baseline(train_fit_df, val_df, eval_subset)
if "svm_metrics" not in globals():
    svm_metrics, svm_class_df, svm_merged, svm_pred, svm_thresholds = tfidf_linearsvm_baseline(train_fit_df, val_df, eval_subset)
if "wc_lr_metrics" not in globals():
    wc_lr_metrics, wc_lr_class_df, wc_lr_merged, wc_lr_pred, wc_lr_thresholds = wordchar_logreg_baseline(train_fit_df, val_df, eval_subset)
if "wc_svm_metrics" not in globals():
    wc_svm_metrics, wc_svm_class_df, wc_svm_merged, wc_svm_pred, wc_svm_thresholds = wordchar_linearsvm_baseline(train_fit_df, val_df, eval_subset)
if "cc_metrics" not in globals():
    cc_metrics, cc_class_df, cc_merged, cc_pred, cc_thresholds = classifier_chain_baseline(train_fit_df, val_df, eval_subset)


def bootstrap_micro_f1(pred_df, true_df, B=300, seed=SEED):
    merged = pred_df.merge(
        true_df[["id"] + CATEGORIES],
        on="id",
        how="inner",
        suffixes=("_pred", "_true")
    ).reset_index(drop=True)
    y_true = merged[[f"{c}_true" for c in CATEGORIES]].values
    y_pred = merged[[f"{c}_pred" for c in CATEGORIES]].values

    rng = np.random.default_rng(seed)
    n = len(merged)
    stats = []
    for _ in range(B):
        idx = rng.integers(0, n, size=n)
        stats.append(f1_score(y_true[idx], y_pred[idx], average="micro", zero_division=0))
    lo, hi = np.percentile(stats, [2.5, 97.5])
    return float(lo), float(hi)


def metrics_table(*metric_dicts):
    rows = []
    pred_lookup = {
        "LLM Zero-shot": zero_preds,
        "LLM Few-shot": few_preds,
        "Baseline: All-zero": zero_base_pred,
        "Baseline: TFIDF+LogReg (tuned)": lr_base_pred,
        "Baseline: TFIDF+LinearSVM (tuned)": svm_pred,
        "Baseline: WordCharTFIDF+LogReg (tuned)": wc_lr_pred,
        "Baseline: WordCharTFIDF+LinearSVM (tuned)": wc_svm_pred,
        "Baseline: ClassifierChain+LogReg (tuned)": cc_pred,
    }
    for m in metric_dicts:
        lo, hi = bootstrap_micro_f1(pred_lookup[m["name"]], eval_subset)
        row = dict(m)
        row["micro_f1_ci_low"] = lo
        row["micro_f1_ci_high"] = hi
        rows.append(row)
    return pd.DataFrame(rows).sort_values("micro_f1", ascending=False).reset_index(drop=True)

results_summary_df = metrics_table(
    zero_metrics,
    few_metrics,
    zero_base_metrics,
    lr_base_metrics,
    svm_metrics,
    wc_lr_metrics,
    wc_svm_metrics,
    cc_metrics,
)

display(results_summary_df)

def print_tidy_report(pred_df, true_df, name="LLM Few-shot"):
    merged = pred_df.merge(
        true_df[["id"] + CATEGORIES],
        on="id",
        how="inner",
        suffixes=("_pred", "_true")
    )
    y_true = merged[[f"{c}_true" for c in CATEGORIES]].values
    y_pred = merged[[f"{c}_pred" for c in CATEGORIES]].values
    class_df = per_class_metrics_df(y_true, y_pred)

    W = 72
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    print()
    print("=" * W)
    print(f"{name.upper()} EVALUATION REPORT".center(W))
    print("=" * W)
    print(f"Generated : {now}   Model     : {MODEL}")
    print(f"Few-shot variant: {FEWSHOT_VARIANT}")
    print(f"Rows eval : {len(merged):,}")
    print()
    print("── GLOBAL METRICS ──")
    print(f"  Micro  Prec={precision_score(y_true, y_pred, average='micro', zero_division=0):.4f}  Rec={recall_score(y_true, y_pred, average='micro', zero_division=0):.4f}  F1={f1_score(y_true, y_pred, average='micro', zero_division=0):.4f}")
    print(f"  Macro  Prec={precision_score(y_true, y_pred, average='macro', zero_division=0):.4f}  Rec={recall_score(y_true, y_pred, average='macro', zero_division=0):.4f}  F1={f1_score(y_true, y_pred, average='macro', zero_division=0):.4f}")
    print()
    print(f"  Exact Match Acc : {accuracy_score(y_true, y_pred):.4f}")
    print(f"  Hamming Loss    : {hamming_loss(y_true, y_pred):.4f}")
    print(f"  Jaccard(macro)  : {jaccard_score(y_true, y_pred, average='macro', zero_division=0):.4f}")
    print(f"  Jaccard(samples): {jaccard_score(y_true, y_pred, average='samples', zero_division=0):.4f}")
    print()
    print("── PER-LABEL METRICS ──")
    print()
    hdr = f"  {'Label':<20} {'Prec':>6}  {'Rec':>6}  {'F1':>6}  {'TP':>6}  {'FP':>6}  {'FN':>6}  {'TN':>6}  {'Support':>7}"
    print(hdr)
    print("  " + "-" * 89)

    for _, row in class_df.iterrows():
        star = " ★" if row["precision_priority"] else ""
        label = row["label"] + star
        print(f"  {label:<22} {row['precision']:>6.4f}  {row['recall']:>6.4f}  {row['f1']:>6.4f}  {int(row['tp']):>6}  {int(row['fp']):>6}  {int(row['fn']):>6}  {int(row['tn']):>6}  {int(row['support']):>7}")

    print()
    print("  ★ = Precision-priority label")
    print()
    print("── PRECISION-PRIORITY SUMMARY ──")
    priority_df = class_df[class_df["precision_priority"]]
    for _, row in priority_df.iterrows():
        print(f"  [{row['label']}]  Precision={row['precision']:.4f}  Recall={row['recall']:.4f}  FalsePositiveRate={row['false_positive_rate']:.4f}  FP={int(row['fp'])}  FN={int(row['fn'])}")
    print()

def save_tidy_outputs(pred_df, true_df, prefix="eval2000", name="fewshot"):
    merged = pred_df.merge(
        true_df[["id", "comment_text"] + CATEGORIES],
        on="id",
        how="inner",
        suffixes=("_pred", "_true")
    ).copy()

    merged["true_labels"] = merged.apply(lambda r: labels_to_text({c: r[f"{c}_true"] for c in CATEGORIES}), axis=1)
    merged["pred_labels"] = merged.apply(lambda r: labels_to_text({c: r[f"{c}_pred"] for c in CATEGORIES}), axis=1)
    merged["exact_match"] = np.where(merged["true_labels"] == merged["pred_labels"], "✅", "❌")

    tidy_cols = ["id", "comment_text", "true_labels", "pred_labels", "exact_match"]
    for c in CATEGORIES:
        merged[f"match_{c}"] = np.where(
            merged[f"{c}_true"] == merged[f"{c}_pred"],
            "✅",
            np.where(merged[f"{c}_pred"] == 1, "FP", "FN")
        )
        tidy_cols.extend([f"{c}_true", f"{c}_pred", f"match_{c}"])

    tidy_df = merged[tidy_cols].copy()
    csv_path = f"{prefix}_{name}_tidy.csv"
    tidy_df.to_csv(csv_path, index=False)
    print(f"Tidy CSV saved -> {csv_path}")

    try:
        import openpyxl
        from openpyxl.styles import PatternFill, Font, Alignment
        from openpyxl.utils import get_column_letter

        xlsx_path = f"{prefix}_{name}_tidy.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Predictions Summary"

        green = PatternFill("solid", fgColor="C6EFCE")
        red = PatternFill("solid", fgColor="FFC7CE")
        yellow = PatternFill("solid", fgColor="FFEB9C")
        header_fill = PatternFill("solid", fgColor="4472C4")
        white_font = Font(bold=True, color="FFFFFF")

        headers = ["id", "comment_text", "true_labels", "pred_labels", "exact_match"]
        for c in CATEGORIES:
            headers.extend([f"{c}_true", f"{c}_pred", f"match_{c}"])
        ws.append(headers)

        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = white_font
            cell.alignment = Alignment(horizontal="center", wrap_text=True)

        for _, row in tidy_df.iterrows():
            ws.append([row[h] for h in headers])
            row_num = ws.max_row
            for col_idx, h in enumerate(headers, start=1):
                cell = ws.cell(row=row_num, column=col_idx)
                if h == "exact_match":
                    cell.fill = green if row[h] == "✅" else red
                elif h.startswith("match_"):
                    if row[h] == "✅":
                        cell.fill = green
                    elif row[h] == "FP":
                        cell.fill = red
                    else:
                        cell.fill = yellow

        widths = {"A": 16, "B": 80, "C": 24, "D": 24, "E": 12}
        for col_letter, width in widths.items():
            ws.column_dimensions[col_letter].width = width
        for i in range(6, len(headers) + 1):
            ws.column_dimensions[get_column_letter(i)].width = 14
        ws.freeze_panes = "A2"
        wb.save(xlsx_path)
        print(f"Tidy Excel saved -> {xlsx_path}")

    except ImportError:
        print("openpyxl not installed; skipped Excel tidy output.")

In [ ]:
# ==========================================
# DETAILED ERROR ANALYSIS (KEEP FUNCTION NAME)
# ==========================================

def detailed_error_analysis(pred_df, true_df, out_prefix="run"):
    merged = pred_df.merge(
        true_df[["id", "comment_text"] + CATEGORIES],
        on="id",
        suffixes=("_pred", "_true")
    )

    error_summary = []
    for c in CATEGORIES:
        true = merged[f"{c}_true"]
        pred = merged[f"{c}_pred"]
        false_positive = ((true == 0) & (pred == 1)).sum()
        false_negative = ((true == 1) & (pred == 0)).sum()
        error_summary.append({
            "label": c,
            "false_positive": int(false_positive),
            "false_negative": int(false_negative),
            "total_errors": int(false_positive + false_negative)
        })

    error_summary_df = pd.DataFrame(error_summary).sort_values("total_errors", ascending=False)

    def describe_error(row):
        errors = []
        for c in CATEGORIES:
            t = row[f"{c}_true"]
            p = row[f"{c}_pred"]
            if t != p:
                errors.append(f"{c}:{'FN' if (t==1 and p==0) else 'FP'}")
        return "; ".join(errors)

    merged["error_description"] = merged.apply(describe_error, axis=1)
    error_cases = merged[merged["error_description"] != ""].copy()

    # Hardest cases first = more errors + longer comments
    error_cases["error_count"] = error_cases["error_description"].str.count(";") + 1
    error_cases["text_len"] = error_cases["comment_text"].fillna("").astype(str).str.len()
    error_cases = error_cases.sort_values(["error_count", "text_len"], ascending=[False, False])

    error_cases.to_csv(f"{out_prefix}_error_analysis_detailed.csv", index=False)
    error_summary_df.to_csv(f"{out_prefix}_error_summary_stats.csv", index=False)

    print(f"Saved: {out_prefix}_error_analysis_detailed.csv, {out_prefix}_error_summary_stats.csv")
    return error_cases, error_summary_df

zero_error_cases, zero_error_summary = detailed_error_analysis(zero_preds, eval_subset, out_prefix=f"{SAVE_PREFIX}_zero")
few_error_cases,  few_error_summary  = detailed_error_analysis(few_preds,  eval_subset, out_prefix=f"{SAVE_PREFIX}_few")
lr_error_cases,   lr_error_summary   = detailed_error_analysis(lr_base_pred, eval_subset, out_prefix=f"{SAVE_PREFIX}_lr")

zero_error_summary.head(10), few_error_summary.head(10), lr_error_summary.head(10)

In [ ]:
# ==========================================
# SAVE RESULTS
# ==========================================

def save_results(prefix=SAVE_PREFIX):
    zero_preds.to_csv(f"{prefix}_zero_shot_predictions.csv", index=False)
    few_preds.to_csv(f"{prefix}_few_shot_predictions.csv", index=False)
    lr_base_pred.to_csv(f"{prefix}_tfidf_logreg_predictions.csv", index=False)
    svm_pred.to_csv(f"{prefix}_tfidf_linearsvm_predictions.csv", index=False)
    wc_lr_pred.to_csv(f"{prefix}_wordchar_logreg_predictions.csv", index=False)
    cc_pred.to_csv(f"{prefix}_classifierchain_predictions.csv", index=False)

    eval_subset.to_csv(f"{prefix}_evaluation_subset.csv", index=False)
    prompt_pool_label_summary.to_csv(f"{prefix}_prompt_pool_label_summary.csv", index=False)
    eval_label_summary.to_csv(f"{prefix}_eval_label_summary.csv", index=False)
    challenge_subset.to_csv(f"{prefix}_challenge_subset.csv", index=False)
    val_pilot_df.to_csv(f"{prefix}_validation_pilot_subset.csv", index=False)

    zero_class_df.to_csv(f"{prefix}_zero_per_class_metrics.csv", index=False)
    few_class_df.to_csv(f"{prefix}_few_per_class_metrics.csv", index=False)
    lr_base_class_df.to_csv(f"{prefix}_lr_per_class_metrics.csv", index=False)
    svm_class_df.to_csv(f"{prefix}_svm_per_class_metrics.csv", index=False)
    wc_lr_class_df.to_csv(f"{prefix}_wordchar_lr_per_class_metrics.csv", index=False)
    cc_class_df.to_csv(f"{prefix}_cc_per_class_metrics.csv", index=False)
    results_summary_df.to_csv(f"{prefix}_results_summary.csv", index=False)

    pd.DataFrame([lr_thresholds]).to_csv(f"{prefix}_lr_thresholds.csv", index=False)
    pd.DataFrame([svm_thresholds]).to_csv(f"{prefix}_svm_thresholds.csv", index=False)
    pd.DataFrame([wc_lr_thresholds]).to_csv(f"{prefix}_wordchar_lr_thresholds.csv", index=False)
    pd.DataFrame([cc_thresholds]).to_csv(f"{prefix}_cc_thresholds.csv", index=False)

    pd.DataFrame([
        {**{"slot": ex["slot"], "id": ex["id"], "comment_text": ex["comment_text"]}, **ex["labels"]}
        for ex in fewshot_bank
    ]).to_csv(f"{prefix}_fewshot_bank.csv", index=False)

    save_tidy_outputs(few_preds, eval_subset, prefix=prefix, name="fewshot")
    save_tidy_outputs(zero_preds, eval_subset, prefix=prefix, name="zeroshot")
    save_tidy_outputs(lr_base_pred, eval_subset, prefix=prefix, name="tfidf_logreg")

    print(f"Saved core outputs with prefix '{prefix}'.")

save_results()

In [ ]:
# Optional quick views for the report
print("\nOverall results summary")
display(results_summary_df)

print("\nFew-shot per-class metrics")
display(few_class_df.sort_values(['f1', 'support'], ascending=[False, False]).reset_index(drop=True))

print("\nTop few-shot error categories")
display(few_error_summary)

print_tidy_report(few_preds, eval_subset, name="LLM Few-shot")